twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    #intégration du template de formulaire en bootstrap 4
    form_themes: ['bootstrap_4_layout.html.twig']
